image: "rust:latest"

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  RUSTFLAGS: -Dwarnings

stages:
  - verify
  - test
  - build
  - release

default:
  interruptible: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo
      - target
  before_script:
      - apt update
      - apt install -y openssl pkg-config libxml2-dev libsqlite3-dev 

cargo:fmt:
  stage: verify
  script:
    - rustup component add rustfmt
    - cargo fmt --check

cargo:clippy:
  stage: verify
  script:
    - rustup component add clippy
    - cargo clippy --all-targets 

cargo:test:
  stage: test
  needs: ["cargo:clippy"]
  script:
    - cargo test

build:
  stage: build
  needs: ["cargo:test"]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - VERSION="$CI_COMMIT_TAG"
    - sed -i "s/GIT_VERSION/$VERSION/" Cargo.toml
    - cargo build --release
    - mkdir -p eilmeldung-$VERSION
    - cp target/release/eilmeldung eilmeldung-$VERSION/
    - cp -r examples eilmeldung-$VERSION/
    - tar -czf eilmeldung-$VERSION.tar.gz eilmeldung-$VERSION/
  artifacts:
    paths:
      - eilmeldung-*.tar.gz
    expire_in: never

release_job:
  needs: ["build"]
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: './CHANGELOG.md'
    assets:
      - name: 'Linux binaries'
        filepath: "./eilmeldung-$CI_COMMIT_TAG.tar.gz"
        linktype: 'package'

