image: "rust:latest"

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  RUSTFLAGS: -Dwarnings

stages:
  - verify
  - test
  - build
  - release

.build_deps:
  interruptible: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo
      - target
  before_script:
    - apt update
    - apt install -y openssl pkg-config libxml2-dev libsqlite3-dev llvm clang

cargo:fmt:
  stage: verify
  extends: .build_deps
  script:
    - rustup component add rustfmt
    - cargo fmt --check

cargo:clippy:
  stage: verify
  extends: .build_deps
  script:
    - rustup component add clippy
    - cargo clippy --all-targets

cargo:test:
  stage: test
  extends: .build_deps
  needs: ["cargo:clippy"]
  script:
    - cargo test

cargo:build:
  stage: build
  extends: .build_deps
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/eilmeldung

package:
  stage: build
  extends: .build_deps
  needs: ["cargo:build"]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - VERSION="$CI_COMMIT_TAG"
    - sed -i "s/0\.0\.0/$VERSION/" Cargo.toml
    - mkdir -p eilmeldung-$VERSION
    - cp target/release/eilmeldung eilmeldung-$VERSION/
    - cp -r examples eilmeldung-$VERSION/
    - tar -czf eilmeldung-$VERSION.tar.gz eilmeldung-$VERSION/
  artifacts:
    paths:
      - eilmeldung-*.tar.gz
    expire_in: never

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: './CHANGELOG.md'
    assets:
      links:
        - name: 'Linux binaries'
          filepath: './eilmeldung-$CI_COMMIT_TAG.tar.gz'
          link_type: 'package'
