image: "rust:latest"

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  RUSTFLAGS: -Dwarnings
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/eilmeldung/"

stages:
  - verify
  - test
  - build
  - deploy
  - release

.build_deps:
  interruptible: true
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cargo
      - target
  before_script:
    - apt update
    - apt install -y openssl pkg-config libxml2-dev libsqlite3-dev llvm clang

.cargo:fmt:
  stage: verify
  extends: .build_deps
  script:
    - rustup component add rustfmt
    - cargo fmt --check

.cargo:clippy:
  stage: verify
  extends: .build_deps
  script:
    - rustup component add clippy
    - cargo clippy --all-targets

.cargo:test:
  stage: test
  extends: .build_deps
  needs: ["cargo:clippy"]
  script:
    - cargo test

cargo:build:
  stage: build
  extends: .build_deps
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/eilmeldung

package:
  stage: build
  extends: .build_deps
  needs: ["cargo:build"]
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - sed -i "s/0\.0\.0/${CI_COMMIT_TAG}/" Cargo.toml
    - mkdir -p eilmeldung-${CI_COMMIT_TAG}
    - cp target/release/eilmeldung eilmeldung-${CI_COMMIT_TAG}/
    - cp -r examples eilmeldung-${CI_COMMIT_TAG}/
    - tar -czf eilmeldung-${CI_COMMIT_TAG}.tar.gz eilmeldung-${CI_COMMIT_TAG}/
  artifacts:
    paths:
      - eilmeldung-${CI_COMMIT_TAG}.tar.gz
    expire_in: "1 week"

publish:
  stage: deploy
  needs: ["package"]
  script:
    - |
      curl --location --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file eilmeldung-${CI_COMMIT_TAG}.tar.gz \
           "${PACKAGE_REGISTRY_URL}/eilmeldung-${CI_COMMIT_TAG}.tar.gz"

release:
  stage: release
  needs: ["publish"]
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: './CHANGELOG.md'
    assets:
      links:
        - name: 'Linux executable'
          url: "${PACKAGE_REGISTRY_URL}"
          filepath: '/eilmeldung-${CI_COMMIT_TAG}.tar.gz'
          link_type: 'package'
